import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {MeshBuilder, Vector3} from "@babylonjs/core";
import React from "react";
import {Engine, Scene} from "react-babylonjs";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div style={{ flex: 1, display: "flex", height: "100vh", width: "100vw" }}>
              <Engine
                  canvasId="sample-canvas"
                  canvasStyle={{ display: "block", width: "100%" }}
              >
                  <Scene>
                      <freeCamera
                          name="camera1"
                          position={new Vector3(0, 5, -10)}
                          // @ts-ignore - doesn't seem like this is working...
                          // setTarget & getTarget exist in TargetCamera, but
                          // this property doesn't seem to be setting properly
                          target={new Vector3(0, 0, 0)}
                      />
                      <hemisphericLight
                          name="light1"
                          intensity={0.7}
                          direction={Vector3.Up()}
                      />
                      <sphere
                          name="sphere1"
                          diameter={2}
                          segments={16}
                          position={new Vector3(0, 3, 0)}
                      />
                      <ground
                          name="ground1"
                          width={6}
                          height={6}
                          subdivisions={2}
                          position={new Vector3(0, 2, 0)}
                      />
                  </Scene>
              </Engine>
          </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://solidwebcode.com" target="_blank" rel="noopener noreferrer">
          Powered by Solid Web Code
        </a>
      </footer>
    </div>
  )
}

export default Home
